language: node_js

node_js:
 - iojs
 - 0.10
 - 0.11
 - 0.12

script: npm run travis

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --yes python3 php5-curl php5-cli

after_script:
  - npm run coverage
